version: "3.8"

services:
  groops-angular:
    image: groops-angular:${VERSION:-latest}
    container_name: groops-angular
    entrypoint: "ng serve --host 0.0.0.0"
    build:
      context: "."
      dockerfile: "Dockerfile"
    restart: always
    network_mode: "host"
