export enum PermissionEnum {
    READ_COMMENT = 'READ_COMMENT',
    WRITE_COMMENT = 'WRITE_COMMENT',
    READ_POST = 'READ_POST',
    WRITE_POST = 'WRITE_POST',
    LIKE_POST = 'LIKE_POST',
    WRITE_GROUP_MESSAGE = 'WRITE_GROUP_MESSAGE',
    READ_GROUP_MESSAGE = 'READ_GROUP_MESSAGE',
    ADD_USER = 'ADD_USER',
    CHANGE_ROLE = 'CHANGE_ROLE',
    DELETE_GROUP = 'DELETE_GROUP',
    REMOVE_USER = 'REMOVE_USER'
}
